apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
spec:
  replicas: 1
  image:
    application: ogomezso/cp-server-connect:7.6.2
    init: confluentinc/confluent-init-container:2.8.3
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub:
          - name: kafka-connect-jms
            owner: confluentinc
            version: 12.2.0
          - name: kafka-connect-datagen
            owner: confluentinc
            version: 0.4.0
          - name: connect-transforms
            owner: confluentinc
            version: latest
  dependencies:
    kafka:
      bootstrapEndpoint: pkc-nq356.eu-south-2.aws.confluent.cloud:9092
      authentication:
        type: plain
        jaasConfig:
          secretRef: ccloud-credentials
      tls:
        enabled: true
        ignoreTrustStoreConfig: true
    schemaRegistry:
      url: https://psrc-w7y3x9.eu-south-2.aws.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: ccloud-sr-credentials